spring:
  application:
    name: naming-center
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: namingcenter
    password: java1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update # 테이블 자동 생성 전략 (none, create, create-drop, update, validate)
    show-sql: true # SQL 쿼리 로그 출력
    properties:
      hibernate:
        "[format_sql]": true # SQL 쿼리 로그 포맷팅 
        dialect: org.hibernate.dialect.OracleDialect # Oracle 12c+ 방언
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1087672790120-mmcgdafbqhuhqejmqnjpa01nk3emu2cm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile # ,로 구분해서 한 줄 배열할 수도 있음 but, 가독성이 조금 떨어질 수 있음
file:
  upload:
     dir: src/main/resources/static/uploads